    # version: '3'
    # services:
    #   web:
    #     build:
    #       context: .
    #       dockerfile: Dockerfile
    #     ports:
    #       - '80:80'


version: '3.8'

services:
  frontend-prod:
    container_name: frontend-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '80:80'